version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scratch"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j945wt4vvbcq"
s3_prefix = "scratch"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
