# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >-
  scratch

Parameters:
  Stage:
    Type: String
    Default: test

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 120
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: my-table
        STAGE: test
        REGION: eu-west-1

Resources:
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  hospitalGetAllCases:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hospital/get-all-cases.handler
      Description: Dispatch responder to location
      Events:
        hospitalGetAllCases:
          Type: Api
          Properties:
            Path: /hospital/cases
            Method: get
            RestApiId: !Ref ApiDeployment

Outputs:
  hospitalGetAllCases:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/started/"
